Repository wp-graphql/wp-graphql-woocommerce, pull requests merged in 2020-01, with the labels that each got.

#211 Better cart mutation support/unsupported type error handling
  includes/connection/class-products.php
  includes/data/connection/class-product-connection-resolver.php
  includes/utils/class-ql-session-handler.php
Labels: bugfix, enhancement

#212 More customer improvements.
  includes/class-jwt-auth-schema-filters.php
  includes/class-wp-graphql-woocommerce.php
  includes/connection/class-orders.php
  includes/data/mutation/class-customer-mutation.php
  includes/mutation/class-customer-register.php
  tests/wpunit/CustomerQueriesTest.php
Labels: bugfix, enhancement

#213 Updates some product fields' access levels
  includes/model/class-product-variation.php
  includes/model/class-product.php
  tests/_support/Helper/crud-helpers/product.php
Labels: bugfix, enhancement

#214 allow optional password creation for registerCustomer
  includes/mutation/class-customer-register.php
Labels: enhancement

#215 Pagination implemented on cart connection
  includes/connection/class-cart-items.php
  includes/data/class-factory.php
  includes/data/connection/class-cart-item-connection-resolver.php
  includes/data/connection/class-product-connection-resolver.php
  tests/_support/Helper/crud-helpers/cart.php
  tests/wpunit/CartQueriesTest.php
Labels: enhancement, new fields

#216 Release v0.3.3
  .travis.yml
  README.md
  README.txt
  includes/connection/class-cart-items.php
  includes/data/connection/class-cart-item-connection-resolver.php
  includes/data/connection/class-coupon-connection-resolver.php
  includes/data/connection/class-customer-connection-resolver.php
  includes/data/connection/class-order-connection-resolver.php
  includes/data/connection/class-product-connection-resolver.php
  includes/data/connection/class-refund-connection-resolver.php
  includes/data/connection/class-tax-rate-connection-resolver.php
  includes/data/connection/trait-wc-connection-functions.php
  includes/data/loader/class-wc-post-crud-loader.php
  includes/data/mutation/class-checkout-mutation.php
  includes/data/mutation/class-order-mutation.php
  includes/mutation/class-cart-apply-coupon.php
  includes/mutation/class-checkout.php
  includes/mutation/class-order-create.php
  includes/mutation/class-order-delete-items.php
  includes/mutation/class-order-delete.php
  includes/mutation/class-order-update.php
  includes/type/object/class-order-type.php
  tests/_support/Helper/crud-helpers/coupon.php
  tests/wpunit/CartMutationsTest.php
  tests/wpunit/CartQueriesTest.php
  tests/wpunit/CheckoutMutationsTest.php
  tests/wpunit/ConnectionPaginationTest.php
  tests/wpunit/CustomerQueriesTest.php
  tests/wpunit/MetaDataQueriesTest.php
  tests/wpunit/OrderQueriesTest.php
  tests/wpunit/RefundQueriesTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  wp-graphql-woocommerce.php
Labels: release-summary

#196 Adds support for the next version of WPGraphQL-JWT-Authentication
  includes/class-jwt-auth-schema-filters.php
Labels: bugfix, enhancement

#198 Adds product reviews
  includes/class-core-schema-filters.php
  includes/class-type-registry.php
  includes/connection/class-product-reviews.php
  includes/connection/class-wc-terms.php
  includes/data/connection/class-product-review-connection-resolver.php
  includes/data/connection/class-wc-term-connection-resolver.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: enhancement, new connections

#195 Feature/product attributes upgrade
  includes/class-type-registry.php
  includes/connection/class-product-attributes.php
  includes/connection/class-wc-terms.php
  includes/data/connection/class-product-attribute-connection-resolver.php
  includes/type/enum/class-product-attribute-types.php
  includes/type/interface/class-product-attribute.php
  includes/type/interface/class-product.php
  includes/type/object/class-product-attribute-type.php
  includes/type/object/class-product-attribute-types.php
  tests/_support/Helper/crud-helpers/product.php
  tests/wpunit/ProductQueriesTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: enhancement, new types

#219 "DownloadableItem" type and connection added.
  .travis.yml
  Dockerfile
  bin/testing-entrypoint.sh
  docker-compose.yml
  includes/class-type-registry.php
  includes/connection/class-downloadable-items.php
  includes/data/class-factory.php
  includes/data/connection/class-downloadable-item-connection-resolver.php
  includes/model/class-order.php
  includes/type/object/class-downloadable-item-type.php
  includes/type/object/class-order-type.php
  tests/_support/Helper/GraphQLE2E.php
  tests/_support/Helper/crud-helpers/coupon.php
  tests/_support/Helper/crud-helpers/order.php
  tests/_support/Helper/crud-helpers/product.php
  tests/wpunit/CheckoutMutationsTest.php
  tests/wpunit/ConnectionPaginationTest.php
  tests/wpunit/DownloadableItemQueriesTest.php
  tests/wpunit/OrderMutationsTest.php
  tests/wpunit/OrderQueriesTest.php
  tests/wpunit/ProductQueriesTest.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
Labels: bugfix, enhancement, new connections, new types

#217 Release v0.4.0
  .travis.yml
  Dockerfile
  README.txt
  bin/testing-entrypoint.sh
  docker-compose.yml
  includes/class-core-schema-filters.php
  includes/class-jwt-auth-schema-filters.php
  includes/class-type-registry.php
  includes/connection/class-downloadable-items.php
  includes/connection/class-product-attributes.php
  includes/connection/class-product-reviews.php
  includes/connection/class-wc-terms.php
  includes/data/class-factory.php
  includes/data/connection/class-downloadable-item-connection-resolver.php
  includes/data/connection/class-product-attribute-connection-resolver.php
  includes/data/connection/class-product-review-connection-resolver.php
  includes/data/connection/class-wc-term-connection-resolver.php
  includes/model/class-order.php
  includes/type/enum/class-product-attribute-types.php
  includes/type/interface/class-product-attribute.php
  includes/type/interface/class-product.php
  includes/type/object/class-downloadable-item-type.php
  includes/type/object/class-order-type.php
  includes/type/object/class-product-attribute-type.php
  includes/type/object/class-product-attribute-types.php
  tests/_support/Helper/GraphQLE2E.php
  tests/_support/Helper/crud-helpers/coupon.php
  tests/_support/Helper/crud-helpers/order.php
  tests/_support/Helper/crud-helpers/product.php
  tests/wpunit/CheckoutMutationsTest.php
  tests/wpunit/ConnectionPaginationTest.php
  tests/wpunit/DownloadableItemQueriesTest.php
  tests/wpunit/OrderMutationsTest.php
  tests/wpunit/OrderQueriesTest.php
  tests/wpunit/ProductQueriesTest.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  wp-graphql-woocommerce.php
Labels: enhancement, release-summary, work in progress

#220 Release v0.4.1
  README.txt
  includes/class-type-registry.php
  includes/mutation/class-checkout.php
  includes/type/enum/class-id-type-enums.php
  includes/type/interface/class-product-attribute.php
  includes/type/interface/class-product.php
  includes/type/object/class-coupon-type.php
  includes/type/object/class-order-type.php
  includes/type/object/class-product-types.php
  includes/type/object/class-product-variation-type.php
  includes/type/object/class-refund-type.php
  includes/type/object/class-shipping-method-type.php
  includes/type/object/class-tax-rate-type.php
  tests/wpunit/CouponQueriesTest.php
  tests/wpunit/MetaDataQueriesTest.php
  tests/wpunit/OrderQueriesTest.php
  tests/wpunit/ProductQueriesTest.php
  tests/wpunit/ProductVariationQueriesTest.php
  tests/wpunit/RefundQueriesTest.php
  tests/wpunit/ShippingMethodQueriesTest.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  wp-graphql-woocommerce.php
Labels: release-summary

#221 Fixes introspection query
  includes/type/enum/class-id-type-enums.php
  includes/type/object/class-coupon-type.php
  tests/wpunit/IntrospectionQueryTest.php
Labels: bugfix, enhancement
