Repository wp-graphql/wp-graphql-woocommerce, pull requests merged in 2020-06, with the labels that each got.

#288 Adds support for changes made in WPGraphQL v0.9.0
  tests/wpunit/ProductQueriesTest.php
  tests/wpunit/ProductVariationQueriesTest.php
Labels: continuous integration

#242 Adds Local-Testing Contribution Guides
  .github/workflows/testing-integration.yml
  .github/workflows/wordpress-coding-standards.yml
  docs/content/contributing/2-local-testing.md
  docs/content/contributing/2-local-testing/image-01.png
  docs/content/contributing/2-local-testing/image-02.png
  docs/content/contributing/2-local-testing/image-03.png
  docs/content/contributing/2-local-testing/image-04.png
  docs/content/contributing/2-local-testing/image-05.png
  docs/content/contributing/2-local-testing/image-06.png
  docs/content/contributing/2-local-testing/image-07.png
  includes/type/object/class-cart-type.php
  tests/_support/Helper/crud-helpers/cart.php
Labels: docs

#294 Fixed : missing static keyword for static variable
  includes/data/mutation/class-checkout-mutation.php
Labels: bugfix

#298 Skip conditional added to stripe test
  .github/workflows/testing-integration.yml
  includes/data/class-factory.php
  includes/data/loader/class-wc-cpt-loader.php
  tests/_support/Helper/crud-helpers/cart.php
  tests/wpunit/CartMutationsTest.php
  tests/wpunit/CartQueriesTest.php
  tests/wpunit/CheckoutMutationTest.php
  tests/wpunit/MetaDataQueriesTest.php
  tests/wpunit/PaymentGatewayQueriesTest.php
Labels: dev-ops

#302 Fixes some unit tests
  tests/wpunit/IntrospectionQueryTest.php
  tests/wpunit/ProductQueriesTest.php
Labels: bugfix

#301 Rating input type changed to "Int"
  includes/mutation/class-review-write.php
Labels: bugfix
